name: runner_info
description: Gather diagnostic information about the self hosted Linux runner.
author: bwhitehead0
inputs:
  detail-level:
    description: Detail level of information.
    required: false
    default: short
outputs:
  runner-info:
    description: Runner information.
runs:
  using: 'composite'
  steps:
    - run: ${{ github.action_path }}/assets/runner_info.sh
      shell: bash