name: runner_info
description: Gather diagnostic information about the self hosted Linux runner.
author: bwhitehead0
inputs:
  detail-level:
    description: Detail level of information. (short, full)
    required: false
    default: short
outputs:
  runner-info:
    description: Runner information.
    value: ${{ steps.gather-info.outputs.runner_info }}
runs:
  using: 'composite'
  steps:
    - name: Gather runner info
      id: gather-info
      # run: echo runner_info=${{ github.action_path }}/assets/runner_info.sh >> $GITHUB_OUTPUT
      run: ${{ github.action_path }}/assets/runner_info.sh
      shell: bash
      env:
        INPUT_DETAIL_LEVEL: ${{ inputs.detail-level }}

branding:
  icon: 'info'
  color: 'green'