on:
  push:

name: "ShellCheck"
permissions:
  contents: read

jobs:
  shellcheck:
    name: Shellcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ github.token }}
      - name: Run ShellCheck
        uses: bwhitehead0/action-shellcheck@master
